substitutions:
  name: "localbytes-bulb-9w-rgbct"
  friendly_name: "Local Bytes RGBCT Bulb"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
        
esp8266:
  board: esp8285
  restore_from_flash: true

ota:

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name}"
    password: !secret ap_password

web_server:
  port: 80
  
captive_portal:

light:
  - platform: rgbww
    name: none
    id: bulb
    restore_mode: ALWAYS_ON
    warm_white: warm_white
    cold_white: white
    red: red
    green: green
    blue: blue
    
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    color_interlock: true

#4, 5, 12, 13, 14
output:
  - platform: esp8266_pwm
    id: red
    pin: GPIO4
    
  - platform: esp8266_pwm
    id: green
    pin: GPIO12
    
  - platform: esp8266_pwm
    id: blue
    pin: GPIO14
    
  - platform: esp8266_pwm
    id: white
    pin: GPIO5
    
  - platform: esp8266_pwm
    id: warm_white
    pin: GPIO13 
   
sensor:
  # WiFi Signal Sensor
  - platform: wifi_signal
    name: "WiFi Status"
    update_interval: 60s
